# Generated by Django 3.1.8 on 2023-04-10 04:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(db_column='name', on_delete=builtins.callable, to='agent_api.person'),
        ),
    ]
