# Generated by Django 3.1.8 on 2023-04-10 04:49

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_auto_20230409_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(on_delete=builtins.callable, to='agent_api.person'),
        ),
    ]
